package com.redhat.sgutierr.rulesinsurancedemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Driver implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "DRIVER_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "DRIVER_ID_SEQ", name = "DRIVER_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Description("Applicant name")
   @org.kie.api.definition.type.Label("Driver name")
   private java.lang.String driverName;

   @org.kie.api.definition.type.Label("Age")
   private java.lang.Integer age;

   @org.kie.api.definition.type.Label("SSN")
   private java.lang.String ssn;

   @org.kie.api.definition.type.Label("dlNumber")
   private java.lang.String dlNumber;

   @org.kie.api.definition.type.Label("Number of accidents")
   private java.lang.Integer numberOfAccidents;

   @org.kie.api.definition.type.Label("NumberOfTickets")
   private java.lang.Integer numberOfTickets;

   @org.kie.api.definition.type.Label("creditScore")
   private java.lang.Integer creditScore;

   @org.kie.api.definition.type.Label(value = "Score")
   private double rulesScore;

   public Driver()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getDriverName()
   {
      return this.driverName;
   }

   public void setDriverName(java.lang.String driverName)
   {
      this.driverName = driverName;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.String getSsn()
   {
      return this.ssn;
   }

   public void setSsn(java.lang.String ssn)
   {
      this.ssn = ssn;
   }

   public java.lang.String getDlNumber()
   {
      return this.dlNumber;
   }

   public void setDlNumber(java.lang.String dlNumber)
   {
      this.dlNumber = dlNumber;
   }

   public java.lang.Integer getNumberOfAccidents()
   {
      return this.numberOfAccidents;
   }

   public void setNumberOfAccidents(java.lang.Integer numberOfAccidents)
   {
      this.numberOfAccidents = numberOfAccidents;
   }

   public java.lang.Integer getNumberOfTickets()
   {
      return this.numberOfTickets;
   }

   public void setNumberOfTickets(java.lang.Integer numberOfTickets)
   {
      this.numberOfTickets = numberOfTickets;
   }

   public java.lang.Integer getCreditScore()
   {
      return this.creditScore;
   }

   public void setCreditScore(java.lang.Integer creditScore)
   {
      this.creditScore = creditScore;
   }

   public double getRulesScore()
   {
      return this.rulesScore;
   }

   public void setRulesScore(double rulesScore)
   {
      this.rulesScore = rulesScore;
   }

   public Driver(java.lang.Long id, java.lang.String driverName,
         java.lang.Integer age, java.lang.String ssn, java.lang.String dlNumber,
         java.lang.Integer numberOfAccidents, java.lang.Integer numberOfTickets,
         java.lang.Integer creditScore, double rulesScore)
   {
      this.id = id;
      this.driverName = driverName;
      this.age = age;
      this.ssn = ssn;
      this.dlNumber = dlNumber;
      this.numberOfAccidents = numberOfAccidents;
      this.numberOfTickets = numberOfTickets;
      this.creditScore = creditScore;
      this.rulesScore = rulesScore;
   }

}