package com.redhat.sgutierr.rulesinsurancedemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Policy implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "POLICY_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "POLICY_ID_SEQ", name = "POLICY_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Request Date")
   private java.util.Date requestDate;

   @org.kie.api.definition.type.Label("Policy Type")
   private java.lang.String policyType;

   @org.kie.api.definition.type.Label("VehicleYear")
   private java.lang.Integer vehicleYear;

   @org.kie.api.definition.type.Label("Price")
   private java.lang.Integer price;

   @org.kie.api.definition.type.Label("priceDiscount")
   private java.lang.Integer priceDiscount;

   @javax.persistence.ManyToOne(cascade = { javax.persistence.CascadeType.ALL }, fetch = javax.persistence.FetchType.EAGER)
   @org.kie.api.definition.type.Label("Driver")
   private com.redhat.sgutierr.rulesinsurancedemo.Driver driver;

   @org.kie.api.definition.type.Label(value = "Coverage")
   private java.lang.String coverage;

   public Policy()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.util.Date getRequestDate()
   {
      return this.requestDate;
   }

   public void setRequestDate(java.util.Date requestDate)
   {
      this.requestDate = requestDate;
   }

   public java.lang.String getPolicyType()
   {
      return this.policyType;
   }

   public void setPolicyType(java.lang.String policyType)
   {
      this.policyType = policyType;
   }

   public java.lang.Integer getVehicleYear()
   {
      return this.vehicleYear;
   }

   public void setVehicleYear(java.lang.Integer vehicleYear)
   {
      this.vehicleYear = vehicleYear;
   }

   public java.lang.Integer getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.Integer price)
   {
      this.price = price;
   }

   public java.lang.Integer getPriceDiscount()
   {
      return this.priceDiscount;
   }

   public void setPriceDiscount(java.lang.Integer priceDiscount)
   {
      this.priceDiscount = priceDiscount;
   }

   public com.redhat.sgutierr.rulesinsurancedemo.Driver getDriver()
   {
      return this.driver;
   }

   public void setDriver(com.redhat.sgutierr.rulesinsurancedemo.Driver driver)
   {
      this.driver = driver;
   }

   public java.lang.String getCoverage()
   {
      return this.coverage;
   }

   public void setCoverage(java.lang.String coverage)
   {
      this.coverage = coverage;
   }

   public Policy(java.lang.Long id, java.util.Date requestDate,
         java.lang.String policyType, java.lang.Integer vehicleYear,
         java.lang.Integer price, java.lang.Integer priceDiscount,
         com.redhat.sgutierr.rulesinsurancedemo.Driver driver,
         java.lang.String coverage)
   {
      this.id = id;
      this.requestDate = requestDate;
      this.policyType = policyType;
      this.vehicleYear = vehicleYear;
      this.price = price;
      this.priceDiscount = priceDiscount;
      this.driver = driver;
      this.coverage = coverage;
   }

}