package com.redhat.sgutierr.rulesinsurancedemo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Rejection implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "REJECTION_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "REJECTION_ID_SEQ", name = "REJECTION_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Cause")
   private java.lang.String cause;

   public Rejection()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getCause()
   {
      return this.cause;
   }

   public void setCause(java.lang.String cause)
   {
      this.cause = cause;
   }

   public Rejection(java.lang.Long id, java.lang.String cause)
   {
      this.id = id;
      this.cause = cause;
   }

}